const fs = require('fs');
const axios = require('axios');
const { GoogleGenerativeAI } = require('@google/generative-ai');
const AiChatSession = require('../models/AiChatSession');
const Appointment = require('../models/Appointment');

// @desc    Analyze symptoms using Google Gemini API
// @route   POST /api/ai/analyze-symptoms
// @access  Private
exports.analyzeSymptoms = async (req, res) => {
  try {
    const { symptoms } = req.body;

    if (!symptoms) {
      return res.status(400).json({ success: false, error: 'Please enter symptoms description' });
    }

    const symptomsText = Array.isArray(symptoms) ? symptoms.join(', ') : symptoms;

    // Fallback if no GEMINI_API_KEY
    if (!process.env.GEMINI_API_KEY) {
      console.warn('GEMINI_API_KEY not found in env variables. Falling back to local mock analyzer.');
      const lowerSymptoms = symptomsText.toLowerCase();
      let possibleConditions = ['General Exhaustion', 'Viral Syndrome'];
      let recommendedSpecialist = 'General Physician';
      let homeCareSuggestions = ['Drink plenty of water', 'Get adequate rest', 'Monitor temperature'];

      if (lowerSymptoms.includes('fever') || lowerSymptoms.includes('cough') || lowerSymptoms.includes('cold')) {
        possibleConditions = ['Common Flu', 'Viral Fever', 'Upper Respiratory Tract Infection'];
        recommendedSpecialist = 'General Physician';
        homeCareSuggestions = ['Warm saline gargles', 'Stay hydrated', 'Steam inhalation', 'Paracetamol for fever relief if prescribed'];
      } else if (lowerSymptoms.includes('migraine') || lowerSymptoms.includes('headache') || lowerSymptoms.includes('sensory')) {
        possibleConditions = ['Tension Headache', 'Migraine Attack', 'Sinus Congestion'];
        recommendedSpecialist = 'Neurologist';
        homeCareSuggestions = ['Rest in a quiet, dark room', 'Apply cold compress to forehead', 'Avoid screen time'];
      }

      return res.status(200).json({
        success: true,
        data: {
          possibleConditions,
          recommendedSpecialist,
          homeCareSuggestions,
          disclaimer: 'This symptom analysis is generated by AI and is for educational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment.',
        },
      });
    }

    const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
    const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });

    const prompt = `You are an expert AI clinical medical assistant. A patient is reporting the following symptoms:
"${symptomsText}"

Perform a clinical analysis of these symptoms. You MUST respond in valid JSON format. The response must be a single JSON object with precisely these keys:
{
  "possibleConditions": ["list of 2-4 possible general conditions"],
  "recommendedSpecialist": "Single string name of recommended specialist - choose from: General Physician, Cardiologist, Dermatologist, Pediatrician, Neurologist",
  "homeCareSuggestions": ["list of 3-4 initial home care/first aid steps"],
  "disclaimer": "AI medical disclaimer stating this is not a doctor"
}

Do not include any markdown format blocks, wrap the JSON in \`\`\`json \`\`\` code fence, or provide any text surrounding the JSON. Output only the pure JSON text.`;

    const result = await model.generateContent(prompt);
    const response = await result.response;
    let text = response.text().trim();

    if (text.startsWith('```json')) text = text.substring(7);
    if (text.endsWith('```')) text = text.substring(0, text.length - 3);
    text = text.trim();

    const analysis = JSON.parse(text);

    return res.status(200).json({
      success: true,
      data: analysis,
    });
  } catch (error) {
    console.error('Error analyzing symptoms:', error.message);
    res.status(500).json({ success: false, error: 'Failed to complete AI analysis. ' + error.message });
  }
};

// @desc    Conversational AI Chat Assistant
// @route   POST /api/ai/chat
// @access  Private (Patient only)
exports.chatWithAi = async (req, res) => {
  try {
    const { message } = req.body;
    if (!message) {
      return res.status(400).json({ success: false, error: 'Message content is required' });
    }

    // Find or create user chat session history
    let session = await AiChatSession.findOne({ patient: req.user.id });
    if (!session) {
      session = await AiChatSession.create({ patient: req.user.id, messages: [] });
    }

    // Keep memory history bounded (last 10 messages for context size control)
    const recentMessages = session.messages.slice(-10);

    // Default mock response if key is missing
    if (!process.env.GEMINI_API_KEY) {
      const lowerMsg = message.toLowerCase();
      let responseText = "I am the AegisCare AI Assistant. How can I help you understand your health conditions today?";
      let emergency = false;

      if (lowerMsg.includes('chest pain') || lowerMsg.includes('breathing') || lowerMsg.includes('unconscious') || lowerMsg.includes('sos')) {
        responseText = "[EMERGENCY_ALERT] You are describing potentially severe symptoms. Seek emergency care immediately or click the Emergency SOS panic button.";
        emergency = true;
      } else if (lowerMsg.includes('paracetamol') || lowerMsg.includes('medicine')) {
        responseText = "Paracetamol (acetaminophen) is commonly used to treat mild fever and body pain. Always consult a general physician for correct dosages.";
      } else if (lowerMsg.includes('migraine') || lowerMsg.includes('headache')) {
        responseText = "Migraines present as severe headaches, often with nausea and screen sensitivity. You should consult a Neurologist for clinical advice.";
      }

      // Save messages
      session.messages.push({ role: 'user', content: message });
      session.messages.push({ role: 'model', content: responseText });
      await session.save();

      return res.status(200).json({
        success: true,
        response: responseText,
        emergencyDetected: emergency,
      });
    }

    const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
    const chatModel = genAI.getGenerativeModel({ 
      model: 'gemini-1.5-flash',
      systemInstruction: `You are AegisCare's Advanced AI Medical Assistant. Your goals:
1. Explain medical diseases, symptoms, and healthcare guidelines.
2. Explain medicines (standard usage, side effects, precautions).
3. Suggest specialist doctors (General Physician, Cardiologist, Dermatologist, Pediatrician, Neurologist).
4. Explain lab test values (e.g., CBC ranges, glucose levels) in clear, plain language.
5. CRITICAL: If the user's message indicates a life-threatening medical emergency (e.g. severe crushing chest pain, difficulty breathing, severe bleeding, signs of stroke/paralysis, loss of consciousness, choking), you MUST prefix your response with the exact bracketed text "[EMERGENCY_ALERT]" and direct them to click the Emergency SOS tab immediately and contact an ambulance.
6. Emphasize that you are an AI assistant and NOT a doctor.`,
    });

    // Format chat logs history for Gemini chat format
    const chatHistory = recentMessages.map((msg) => ({
      role: msg.role === 'model' ? 'model' : 'user',
      parts: [{ text: msg.content }],
    }));

    // Initiate conversation chat session
    const chatSession = chatModel.startChat({
      history: chatHistory,
    });

    const result = await chatSession.sendMessage(message);
    const responseText = result.response.text();
    const emergencyDetected = responseText.includes('[EMERGENCY_ALERT]');

    // Save to database
    session.messages.push({ role: 'user', content: message });
    session.messages.push({ role: 'model', content: responseText });
    await session.save();

    res.status(200).json({
      success: true,
      response: responseText,
      emergencyDetected,
    });
  } catch (error) {
    console.error('AI chat controller error:', error);
    res.status(500).json({ success: false, error: error.message });
  }
};

// @desc    OCR Scan medical report images or PDFs using Gemini Multimodality
// @route   POST /api/ai/scan-report
// @access  Private (Patient only)
exports.scanReport = async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ success: false, error: 'Please upload a medical report document' });
    }

    if (!process.env.GEMINI_API_KEY) {
      return res.status(200).json({
        success: true,
        data: {
          documentType: 'Prescription / Report',
          patientName: 'Aarav Sharma',
          keyFindings: [
            { metric: 'HbA1c', value: '6.5 %', status: 'Borderline Diabetic' },
            { metric: 'WBC Count', value: '8500 /cumm', status: 'Normal' },
          ],
          interpretation: 'Mock OCR Data: Hemoglobin and vital metrics are within baseline limits. Blood glucose levels indicate early prediabetic tendencies.',
          recommendedNextSteps: 'Discuss glycemic controls with a General Physician.',
        },
      });
    }

    let fileBuffer;
    let mimeType = req.file.mimetype;

    // Read file depending on storage mode (local disk uploads vs Cloudinary URL)
    if (req.file.path.startsWith('http')) {
      // Cloudinary storage mode
      const fileRes = await axios.get(req.file.path, { responseType: 'arraybuffer' });
      fileBuffer = Buffer.from(fileRes.data);
    } else {
      // Local disk storage mode
      fileBuffer = fs.readFileSync(req.file.path);
    }

    const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
    const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });

    const generativePart = {
      inlineData: {
        data: fileBuffer.toString('base64'),
        mimeType: mimeType,
      },
    };

    const prompt = `You are a medical document scanner. Analyze the attached medical report image or PDF and extract its contents. 
You must output a valid JSON document only. The JSON must follow this exact format:
{
  "documentType": "String (e.g. Prescription, Blood Report, MRI, X-Ray)",
  "patientName": "String (Patient name if visible, else 'Unknown')",
  "keyFindings": [
    { "metric": "name of metric / test", "value": "extracted value", "status": "e.g. High / Low / Normal" }
  ],
  "interpretation": "Brief paragraph explaining what these findings mean in simple, layperson terms.",
  "recommendedNextSteps": "Actionable advice (e.g. Consult a cardiologist immediately)"
}

Do not include markdown tags like \`\`\`json or output surrounding text. Provide only the parsed JSON output.`;

    const result = await model.generateContent([prompt, generativePart]);
    const response = await result.response;
    let text = response.text().trim();

    if (text.startsWith('```json')) text = text.substring(7);
    if (text.endsWith('```')) text = text.substring(0, text.length - 3);
    text = text.trim();

    const reportDetails = JSON.parse(text);

    // Clean up local file uploads synchronously if not uploading to Cloudinary
    if (!req.file.path.startsWith('http') && fs.existsSync(req.file.path)) {
      fs.unlinkSync(req.file.path);
    }

    res.status(200).json({
      success: true,
      data: reportDetails,
    });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
};
