version: '3.8'

services:
  database:
    image: mongo:6.0
    container_name: aegiscare-db
    ports:
      - '27017:27017'
    volumes:
      - aegiscare-db-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aegiscare-backend
    ports:
      - '5001:5001'
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://database:27017/telemedicine
      - JWT_SECRET=telemedicine_jwt_super_secret_key_change_me_in_production
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aegiscare-frontend
    ports:
      - '80:80'
    depends_on:
      - backend

volumes:
  aegiscare-db-data:
